### ISSUE TITLE
Project listing e2e tests fail with more than 7 projects

### ISSUE THREAD

**Issue by xla** [oscoin/oscoin-parity-wasm-prototype#71]
For some unknown reason the project listing end-to-end tests fail when the amount of project created for comparison exceed 7. The iteration that fails produces the following log output:

```
 DEBUG web3::transports::http   > [22] Sending: {"jsonrpc":"2.0","method":"personal_signTransaction","params":[{"data":"0xa166557064617465a16f526567697374657250726f6a656374a3646e616d65646e616d656b6465736372697074696f6e6b6465736372697074696f6e67696d675f75726c781a68747470733a2f2f696d672e6578616d706c65732e636f6d2f37","from":"0x727984f8b0f956a2ee83b3c5c09eecff4e8317c8","to":"0xc9990dc273628fd5bbb34dc94a0c8f75b3695740"},""],"id":22} to http://localhost:8545/
 TRACE web3::transports::shared > [22] Request pending.
 TRACE web3::transports::shared > [22] Checking response.
 TRACE web3::transports::shared > [22] Checking response.
 TRACE web3::transports::shared > [22] Extracting result.
 DEBUG web3::transports::http   > [23] Sending: {"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf8c1078083186a0094c9990dc273628fd5bbb34dc94a0c8f75b369574080b860a166557064617465a16f526567697374657250726f6a656374a3646e616d65646e616d656b6465736372697074696f6e6b6465736372697074696f6e67696d675f75726c781a68747470733a2f2f696d672e6578616d706c65732e636f6d2f3746a07621a4ba37d6d106bb00ce99eee72f51338d5b04ad3548fb9db2dbe685d457bca0289d2ac811688be9caf352376d5b30bb82f47dee1b5bf26ce2931b48b7ff6350"],"id":23} to http://localhost:8545/
 TRACE web3::transports::shared > [23] Request pending.
 TRACE web3::transports::shared > [23] Checking response.
 TRACE web3::transports::shared > [23] Checking response.
 TRACE web3::transports::shared > [23] Extracting result.
 DEBUG web3::transports::http   > [24] Sending: {"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xef5f81c3035ea163045f99ce231f45a6a387254634f3b6092748955f4c7b4bbb"],"id":24} to http://localhost:8545/
 TRACE web3::transports::shared > [24] Request pending.
 TRACE web3::transports::shared > [24] Checking response.
 TRACE web3::transports::shared > [24] Checking response.
 TRACE web3::transports::shared > [24] Extracting result.
FAILED

failures:

---- list_projects stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TransactionFailure(0xef5f81c3035ea163045f99ce231f45a6a387254634f3b6092748955f4c7b4bbb)', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x5608afe096e2 - backtrace::backtrace::libunwind::trace::h8a645919789e8d0b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1:     0x5608afe096e2 - backtrace::backtrace::trace_unsynchronized::h2b00fcd64a6db2a8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2:     0x5608afe096e2 - std::sys_common::backtrace::_print::hb48dd402e7e4ee13
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5608afe096e2 - std::sys_common::backtrace::print::h5afe7278b7ee9221
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5608afe096e2 - std::panicking::default_hook::{{closure}}::h06704ce56e3f2eb7
                               at src/libstd/panicking.rs:200
   5:     0x5608afe0935c - std::panicking::default_hook::h79bfafe0b6650e1b
                               at src/libstd/panicking.rs:211
   6:     0x5608afe09e35 - std::panicking::rust_panic_with_hook::h9fb440f8b04cb795
                               at src/libstd/panicking.rs:477
   7:     0x5608afe099d2 - std::panicking::continue_panic_fmt::h50588d05bf19779b
                               at src/libstd/panicking.rs:384
   8:     0x5608afe098c6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5608afe23a8a - core::panicking::panic_fmt::hd2f9751e01df4ba2
                               at src/libcore/panicking.rs:85
  10:     0x5608afe23b87 - core::result::unwrap_failed::hf6f9dcb01951803b
                               at src/libcore/result.rs:1165
  11:     0x5608af275ba0 - core::result::Result<T,E>::unwrap::h17cabdb38d136bd4
                               at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/result.rs:933
  12:     0x5608af270bb1 - end_to_end::list_projects::h96a3a2ef9870ba85
                               at tests/end_to_end.rs:78
  13:     0x5608af28cf3a - end_to_end::list_projects::{{closure}}::hfbcb0d064f698727
                               at tests/end_to_end.rs:59
  14:     0x5608af2800fe - core::ops::function::FnOnce::call_once::hb65f8cdead46a4bc
                               at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/ops/function.rs:227
  15:     0x5608af29817f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h6290d172bb52f107
                               at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/liballoc/boxed.rs:922
  16:     0x5608afe0d4da - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  17:     0x5608af2b297e - std::panicking::try::h43cfd99b2b22e76a
                               at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:275
  18:     0x5608af2b297e - std::panic::catch_unwind::h4f806c3c1d8de2b8
                               at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panic.rs:394
  19:     0x5608af2b297e - test::run_test::run_test_inner::{{closure}}::hfa42f9f3c042c323
                               at src/libtest/lib.rs:1413
  20:     0x5608af2b2269 - test::run_test::run_test_inner::haa86fbaf24f7d82f
                               at src/libtest/lib.rs:1435
  21:     0x5608af2b065d - test::run_test::h8269e281bbf32e4b
                               at src/libtest/lib.rs:1454
  22:     0x5608af2a9546 - test::run_tests::ha4a8ffff8047ddaa
                               at src/libtest/lib.rs:1107
  23:     0x5608af2a9546 - test::run_tests_console::h4a9f91ce9bb2c5ec
                               at src/libtest/lib.rs:957
  24:     0x5608af2a1792 - test::test_main::hd447a67b863bd547
                               at src/libtest/lib.rs:295
  25:     0x5608af2a1fad - test::test_main_static::h64496551eaaed66c
                               at src/libtest/lib.rs:329
  26:     0x5608af271506 - end_to_end::main::h222b28261790bdfa
  27:     0x5608af284d70 - std::rt::lang_start::{{closure}}::h1b90a56d338a546c
                               at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/rt.rs:64
  28:     0x5608afe09863 - std::rt::lang_start_internal::{{closure}}::h886ba8710662e0ce
                               at src/libstd/rt.rs:49
  29:     0x5608afe09863 - std::panicking::try::do_call::hf9383917f63fc317
                               at src/libstd/panicking.rs:296
  30:     0x5608afe0d4da - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  31:     0x5608afe0a3ed - std::panicking::try::h3bb4caf318c2ef30
                               at src/libstd/panicking.rs:275
  32:     0x5608afe0a3ed - std::panic::catch_unwind::h6458650ce45ec87a
                               at src/libstd/panic.rs:394
  33:     0x5608afe0a3ed - std::rt::lang_start_internal::h2228998aafc0f6b1
                               at src/libstd/rt.rs:48
  34:     0x5608af284d49 - std::rt::lang_start::h03a523bedd839aaa
                               at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/rt.rs:64
  35:     0x5608af27153a - main
  36:     0x7f3af6df9ee3 - __libc_start_main
  37:     0x5608af25a18e - _start
  38:                0x0 - <unknown>


failures:
    list_projects

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 2 filtered out

error: test failed, to rerun pass '--test end_to_end'
```

**Comment by xla** [comment]
@rockbmb This is the issue I alluded to on irc.

**Comment by xla** [comment]
First time observed when integrating the recent addition of project listing in #68.

**Comment by rockbmb** [comment]
As I said on the PR, this is most likely because of the gas limit being crossed - since you increased the amount of data each `Project` holds, each `register_project` requires more gas, which means less can be registered in the test.

Either reducing the number of test runs (which you did), increasing the gas or both would work.

**Comment by rockbmb** [comment]
As I said on IRC, the `status` field of `TransactionReceipt` could be more descriptive - being either `0` or `1` does not help in knowing whether the gas limit was reached, or the node failed to process the transaction, or there being malformed data in the transaction fields.

**Comment by xla** [comment]
@rockbmb Thanks for the context! what's the way to increase the gas?
